with stg_sap__bseg as (
  select *
  from main_sap.stg_sap__bseg
),

stg_sap__bkpf as (
  select *
  from main_sap.stg_sap__bkpf
)

select
  cast(i.mandt as VARCHAR) as mandt,
  cast(i.bukrs as VARCHAR) as bukrs,
  cast(i.kunnr as VARCHAR) as kunnr,
  cast(i.umsks as VARCHAR) as umsks,
  cast(i.umskz as VARCHAR) as umskz,
  cast(i.augdt as VARCHAR) as augdt,
  cast(i.augbl as VARCHAR) as augbl,
  cast(i.zuonr as VARCHAR) as zuonr,
  cast(i.gjahr as VARCHAR) as gjahr,
  cast(i.belnr as VARCHAR) as belnr,
  cast(i.buzei as VARCHAR) as buzei,
  cast(h.budat as VARCHAR) as budat,
  cast(h.bldat as VARCHAR) as bldat,
  cast(h.cpudt as VARCHAR) as cpudt,
  cast(h.waers as VARCHAR) as waers,
  cast(h.xblnr as VARCHAR) as xblnr,
  cast(h.blart as VARCHAR) as blart,
  cast(h.monat as VARCHAR) as monat,
  cast(i.bschl as VARCHAR) as bschl,
  cast(i.zumsk as VARCHAR) as zumsk,
  cast(i.shkzg as VARCHAR) as shkzg,
  cast(i.gsber as VARCHAR) as gsber,
  cast(i.tax_country as VARCHAR) as tax_country,
  cast(i.mwskz as VARCHAR) as mwskz,
  cast(i.txdat_from as VARCHAR) as txdat_from,
  cast(i.dmbtr as NUMERIC) as dmbtr,
  cast(i.wrbtr as NUMERIC) as wrbtr,
  cast(i.fcsl as NUMERIC) as fcsl,
  cast(i.rfccur as VARCHAR) as rfccur,
  cast(i.mwsts as NUMERIC) as mwsts,
  cast(i.wmwst as NUMERIC) as wmwst,
  cast(i.lwsts as NUMERIC) as lwsts,
  cast(i.bdiff as NUMERIC) as bdiff,
  cast(i.bdif2 as NUMERIC) as bdif2,
  cast(i.sgtxt as VARCHAR) as sgtxt,
  cast(i.projn as VARCHAR) as projn,
  cast(i.aufnr as VARCHAR) as aufnr,
  cast(i.anln1 as VARCHAR) as anln1,
  cast(i.anln2 as VARCHAR) as anln2,
  cast(i.saknr as VARCHAR) as saknr,
  cast(i.hkont as VARCHAR) as hkont,
  cast(i.fkont as VARCHAR) as fkont,
  cast(i.filkd as VARCHAR) as filkd,
  cast(i.zfbdt as VARCHAR) as zfbdt,
  cast(i.zterm as VARCHAR) as zterm,
  cast(i.zbd1t as NUMERIC) as zbd1t,
  cast(i.zbd2t as NUMERIC) as zbd2t,
  cast(i.zbd3t as NUMERIC) as zbd3t,
  cast(i.zbd1p as NUMERIC) as zbd1p,
  cast(i.zbd2p as NUMERIC) as zbd2p,
  cast(i.skfbt as NUMERIC) as skfbt,
  cast(i.sknto as NUMERIC) as sknto,
  cast(i.wskto as NUMERIC) as wskto,
  cast(i.zlsch as VARCHAR) as zlsch,
  cast(i.zlspr as VARCHAR) as zlspr,
  cast(i.zbfix as VARCHAR) as zbfix,
  cast(i.hbkid as VARCHAR) as hbkid,
  cast(i.bvtyp as VARCHAR) as bvtyp,
  cast(i.rebzg as VARCHAR) as rebzg,
  cast(i.rebzj as VARCHAR) as rebzj,
  cast(i.rebzz as VARCHAR) as rebzz,
  cast(i.samnr as VARCHAR) as samnr,
  cast(i.anfbn as VARCHAR) as anfbn,
  cast(i.anfbj as VARCHAR) as anfbj,
  cast(i.anfbu as VARCHAR) as anfbu,
  cast(i.anfae as VARCHAR) as anfae,
  cast(i.mansp as VARCHAR) as mansp,
  cast(i.mschl as VARCHAR) as mschl,
  cast(i.madat as VARCHAR) as madat,
  cast(i.manst as VARCHAR) as manst,
  cast(i.maber as VARCHAR) as maber,
  cast(h.xnetb as VARCHAR) as xnetb,
  cast(i.xanet as VARCHAR) as xanet,
  cast(i.xcpdd as VARCHAR) as xcpdd,
  cast(i.xinve as VARCHAR) as xinve,
  cast(i.xzahl as VARCHAR) as xzahl,
  cast(i.mwsk1 as VARCHAR) as mwsk1,
  cast(i.txdat_from1 as VARCHAR) as txdat_from1,
  cast(i.tax_country1 as VARCHAR) as tax_country1,
  cast(i.dmbt1 as NUMERIC) as dmbt1,
  cast(i.wrbt1 as NUMERIC) as wrbt1,
  cast(i.hist_tax_factor1 as VARCHAR) as hist_tax_factor1,
  cast(i.mwsk2 as VARCHAR) as mwsk2,
  cast(i.txdat_from2 as VARCHAR) as txdat_from2,
  cast(i.tax_country2 as VARCHAR) as tax_country2,
  cast(i.dmbt2 as NUMERIC) as dmbt2,
  cast(i.wrbt2 as NUMERIC) as wrbt2,
  cast(i.hist_tax_factor2 as VARCHAR) as hist_tax_factor2,
  cast(i.mwsk3 as VARCHAR) as mwsk3,
  cast(i.txdat_from3 as VARCHAR) as txdat_from3,
  cast(i.tax_country3 as VARCHAR) as tax_country3,
  cast(i.dmbt3 as NUMERIC) as dmbt3,
  cast(i.wrbt3 as NUMERIC) as wrbt3,
  cast(i.hist_tax_factor3 as VARCHAR) as hist_tax_factor3,
  cast(i.hist_tax_factor as VARCHAR) as hist_tax_factor,
  cast(i.h_bstat as VARCHAR) as bstat,
  cast(i.vbund as VARCHAR) as vbund,
  cast(i.vbeln as VARCHAR) as vbeln,
  cast(i.rebzt as VARCHAR) as rebzt,
  cast('' as VARCHAR) as infae,
  cast(i.stceg as VARCHAR) as stceg,
  cast(i.egbld as VARCHAR) as egbld,
  cast(i.eglld as VARCHAR) as eglld,
  cast(i.rstgr as VARCHAR) as rstgr,
  cast('' as VARCHAR) as xnoza,
  cast(i.vertt as VARCHAR) as vertt,
  cast(i.vertn as VARCHAR) as vertn,
  cast(i.vbewa as VARCHAR) as vbewa,
  cast(i.wverw as VARCHAR) as wverw,
  cast(i.projk as VARCHAR) as projk,
  cast(i.fipos as VARCHAR) as fipos,
  cast(i.nplnr as VARCHAR) as nplnr,
  cast(i.aufpl as VARCHAR) as aufpl,
  cast(i.aplzl as VARCHAR) as aplzl,
  cast(i.xegdr as VARCHAR) as xegdr,
  cast(i.dmbe2 as NUMERIC) as dmbe2,
  cast(i.dmbe3 as NUMERIC) as dmbe3,
  cast(i.dmb21 as NUMERIC) as dmb21,
  cast(i.dmb22 as NUMERIC) as dmb22,
  cast(i.dmb23 as NUMERIC) as dmb23,
  cast(i.dmb31 as NUMERIC) as dmb31,
  cast(i.dmb32 as NUMERIC) as dmb32,
  cast(i.dmb33 as NUMERIC) as dmb33,
  cast(i.bdif3 as NUMERIC) as bdif3,
  cast(i.xragl as VARCHAR) as xragl,
  cast(i.uzawe as VARCHAR) as uzawe,
  cast(h.xstov as VARCHAR) as xstov,
  cast(i.mwst2 as NUMERIC) as mwst2,
  cast(i.mwst3 as NUMERIC) as mwst3,
  cast(i.sknt2 as NUMERIC) as sknt2,
  cast(i.sknt3 as NUMERIC) as sknt3,
  cast(i.xref1 as VARCHAR) as xref1,
  cast(i.xref2 as VARCHAR) as xref2,
  case
    when coalesce(cast(i._dataaging as VARCHAR),'00000000') = '00000000' then cast('' as VARCHAR)
    else cast('X' as VARCHAR)
  end as xarch,
  cast(i.pswsl as VARCHAR) as pswsl,
  cast(i.pswbt as NUMERIC) as pswbt,
  cast(i.lzbkz as VARCHAR) as lzbkz,
  cast(i.landl as VARCHAR) as landl,
  cast(i.imkey as VARCHAR) as imkey,
  cast(i.vbel2 as VARCHAR) as vbel2,
  cast('000000' as VARCHAR) as vpos2,
  cast(i.posn2 as VARCHAR) as posn2,
  cast(i.eten2 as VARCHAR) as eten2,
  cast(i.fistl as VARCHAR) as fistl,
  cast(i.geber as VARCHAR) as geber,
  cast(i.dabrz as VARCHAR) as dabrz,
  cast(i.xnegp as VARCHAR) as xnegp,
  cast(i.kostl as VARCHAR) as kostl,
  cast(i.rfzei as VARCHAR) as rfzei,
  cast(i.kkber as VARCHAR) as kkber,
  cast(i.empfb as VARCHAR) as empfb,
  cast(i.prctr as VARCHAR) as prctr,
  cast(i.xref3 as VARCHAR) as xref3,
  cast(i.qsskz as VARCHAR) as qsskz,
  cast(i.zinkz as VARCHAR) as zinkz,
  cast(i.dtws1 as NUMERIC) as dtws1,
  cast(i.dtws2 as NUMERIC) as dtws2,
  cast(i.dtws3 as NUMERIC) as dtws3,
  cast(i.dtws4 as NUMERIC) as dtws4,
  cast(i.xpypr as VARCHAR) as xpypr,
  cast(i.kidno as VARCHAR) as kidno,
  cast(i.absbt as VARCHAR) as absbt,
  cast(i.ccbtc as VARCHAR) as ccbtc,
  cast(i.pycur as VARCHAR) as pycur,
  cast(i.pyamt as NUMERIC) as pyamt,
  cast(i.bupla as VARCHAR) as bupla,
  cast(i.secco as VARCHAR) as secco,
  cast(i.cession_kz as VARCHAR) as cession_kz,
  cast(i.ppdiff as NUMERIC) as ppdiff,
  cast(i.ppdif2 as NUMERIC) as ppdif2,
  cast(i.ppdif3 as NUMERIC) as ppdif3,
  cast(i.kblnr as VARCHAR) as kblnr,
  cast(i.kblpos as VARCHAR) as kblpos,
  cast(i.grant_nbr as VARCHAR) as grant_nbr,
  cast(i.gmvkz as VARCHAR) as gmvkz,
  cast(i.srtype as VARCHAR) as srtype,
  cast(h.lotkz as VARCHAR) as lotkz,
  cast(case
    when i.fkber_long = '' then i.fkber
    else i.fkber_long
  end as VARCHAR) as fkber,
  cast(i.intreno as VARCHAR) as intreno,
  cast(i.pprct as VARCHAR) as pprct,
  cast(i.buzid as VARCHAR) as buzid,
  cast(i.auggj as VARCHAR) as auggj,
  cast(i.hktid as VARCHAR) as hktid,
  cast(i.budget_pd as VARCHAR) as budget_pd,
  cast(i.bdgt_account as VARCHAR) as bdgt_account,
  cast(i.re_account as VARCHAR) as re_account,
  cast(i.pays_prov as VARCHAR) as pays_prov,
  cast(i.pays_tran as VARCHAR) as pays_tran,
  cast(i.mndid as VARCHAR) as mndid,
  cast(i.payt_rsn as VARCHAR) as payt_rsn,
  cast(i._dataaging as VARCHAR) as _dataaging,
  cast(i.kontt as VARCHAR) as kontt,
  cast(i.kontl as VARCHAR) as kontl,
  cast('00000000' as VARCHAR) as uebgdat,
  cast(i.vname as VARCHAR) as vname,
  cast(i.egrup as VARCHAR) as egrup,
  cast(i.btype as VARCHAR) as btype,
  cast(h.propmano as VARCHAR) as propmano,
  cast(i.gkont as VARCHAR) as gkont,
  cast(i.gkart as VARCHAR) as gkart,
  cast(i.ghkon as VARCHAR) as ghkon,
  cast(h.awtyp as VARCHAR) as awtyp,
  cast(h.logsystem_sender as VARCHAR) as logsystem_sender,
  cast(h.bukrs_sender as VARCHAR) as bukrs_sender,
  cast(h.belnr_sender as VARCHAR) as belnr_sender,
  cast(h.gjahr_sender as VARCHAR) as gjahr_sender,
  cast(i.buzei_sender as VARCHAR) as buzei_sender,
  cast(i.pendays as INTEGER) as pendays,
  cast(i.j_1tpbupl as VARCHAR) as j_1tpbupl
from stg_sap__bseg as i
left outer join stg_sap__bkpf as h
  on (h.mandt = i.mandt
      and h.bukrs = i.bukrs
      and h.gjahr = i.gjahr
      and h.belnr = i.belnr)
where (cast(i.koart as VARCHAR) = 'D'
  and cast(i.augbl as VARCHAR) = ''
  and not (cast(i.h_bstat as VARCHAR) = 'D')
  and not (cast(i.h_bstat as VARCHAR) = 'M'))
