with base as (

    select *
    from __dbt__cte__int_coep__acdoca_base

)

select
    mandt,
    kokrs,
    belnr,
    buzei,
    rldnr,
    versn,
    budat,
    perio,
    cast((wtgbtr_add - wtgbtr_subtract) as NUMERIC) as wtgbtr,
    cast((wogbtr_add - wogbtr_subtract) as NUMERIC) as wogbtr,
    cast((wkgbtr_add - wkgbtr_subtract) as NUMERIC) as wkgbtr,
    cast((wkfbtr_add - wkfbtr_subtract) as NUMERIC) as wkfbtr,
    cast((pagbtr_add - pagbtr_subtract) as NUMERIC) as pagbtr,
    cast((pafbtr_add - pafbtr_subtract) as NUMERIC) as pafbtr,
    megbtr,
    mefbtr,
    mbgbtr,
    mbfbtr,
    lednr,
    objnr,
    gjahr,
    wrttp,
    kstar,
    hrkft,
    vrgng,
    parob,
    parob1,
    uspob,
    vbund,
    pargb,
    beknz,
    twaer,
    owaer,
    meinh,
    meinb,
    muvflg,
    sgtxt,
    refbz,
    zlenr,
    bw_refbz,
    gkont,
    gkoar,
    werks,
    matnr,
    rbest,
    ebeln,
    ebelp,
    zekkn,
    erlkz,
    pernr,
    paobjnr,
    beltp,
    bukrs,
    gsber,
    fkber,
    scope,
    logsyso,
    pkstar,
    pbukrs,
    pfkber,
    pscope,
    logsysp,
    dabrz,
    bwstrat,
    objnr_hk,
    timestamp_at,
    qmnum,
    geber,
    pgeber,
    grant_nbr,
    pgrant_nbr,
    refbz_fi,
    segment,
    psegment,
    posnr,
    prctr,
    pprct,
    budget_pd,
    pbudget_pd,
    prodper,
    awtyp,
    awkey,
    awsys,
    kwaer,
    accas,
    accasty,
    kostl,
    lstar,
    aufnr,
    autyp,
    pspnr,
    pspid,
    vbeln,
    vbposnr,
    ce4key,
    erkrs,
    paccas,
    paccasty,
    pkostl,
    plstar,
    paufnr,
    pautyp,
    ppspnr,
    ppspid,
    pvbeln,
    pvbposnr,
    pce4key,
    quant1,
    quant2,
    quant3,
    qunit1,
    qunit2,
    qunit3,
    co_accasty_n1,
    co_accasty_n2,
    co_accasty_n3

from base
where not (cast(buzei as VARCHAR) = '000')
