with  __dbt__cte__int_sap__sales_document_header as (


select
	mandt as client_id,
    vbeln as sales_document_id,
    kostl as cost_center_id,
    mahza as number_contacts,
    msr_id as process_identification_number,
    _dataaging as filter_value_aging_date,
    taxk5 as taxclass5_cust_id,
    kvgr4 as customer_group_4_id,
    amtbl as rel_credit_val,
    trvog as transaction_group,
    hb_resdate as resolution_date,
    fmbdat as material_availability_date,
    fsh_vrsn_status as snapshot_status,
    upd_tmstmp as time_stamp,
    auart as sales_document_type_id,
    hb_expdate as expiration_date,
    scheme_grp as group_ref_procedure_id,
    smenr as number_sales_unit_id,
    taxk6 as taxclass6_cust_id,
    fsh_transaction as transaction_number,
    kvgr5 as customer_group_5_id,
    gskst as business_area_from_cost_center_id,
    vkgrp as sales_group_id,
    pay_method as payment_methods,
    ktext as search_term_product_proposal,
    ps_psp_pnr as wbs_element_id,
    faksk as billing_block_in_sd_document_id,
    bnddt as quotation_valid_to_date,
    cmwae as currency_id,
    kokrs as controlling_area_id,
    kunnr as sold_to_party_id,
    betc as business_event_type_code,
    fsh_rereg as release_rule_id,
    tas as treasury_account_symbol,
    cancel_allow as cancellation_allowed,
    fkara as order_rel_bill_type_id,
    taxk7 as taxclass7_cust_id,
    gwldt as guarantee_date,
    psm_budat as posting_in_the_document_date,
    objnr as object_number_at_header_level_id,
    autlf as complete_delivery,
    stwae as statistics_currency_id,
    abhov as pick_up_tim,
    logsysb as logical_system_id,
    fsh_kvgr6 as customer_group_6_id,
    bname as name_orderer,
    taxk8 as taxclass8_cust_id,
    xblnr as reference_document_number,
    mtlaur as marker_low_income_housing_id,
    augru as order_reason_id,
    stafo as update_group_stats_id,
    swenr as business_entity_number_id,
    _xlso_trans_ctxt as _xlso_trans_ctxt,
    abruf_part as check_partner_authorizations,
    cmngv as next_date,
    knkli as credit_account_id,
    spart as division_id,
    proli as dg_mgmt_profile_id,
    enqueue_grp as enqueue_grp,
    vzeit as requested_dely_tim,
    kalcd as proc_camp_determin_id,
    bukrs_vf as company_code_to_be_billed_id,
    fsh_kvgr7 as customer_group_7_id,
    vprgr as proposed_date_type,
    crm_guid as character_field_length_70,
    hityp_pr as hierarchy_type_pricing_id,
    taxk9 as taxclass9_cust_id,
    vgbel as reference_document_id,
    erzet as created_tim,
    ihrez as your_reference,
    submi as collective_number_sd,
    vdatu as requested_delivery_date,
    _xlso_variant_id as _xlso_variant_id,
    abdis as mrp_delivery_schedule_types,
    fsh_kvgr8 as customer_group_8_id,
    ernam as created_by,
    hb_cont_reason as contingency_id,
    netwr as net_val,
    vbkla as original_system,
    vgtyp as preceding_doc_categ,
    sbgrp as credit_rep_group_id,
    stceg_l as tax_destination_country_id,
    fsh_kvgr10 as customer_group_10_id,
    knuma as agreement_id,
    fsh_ss as order_scheduling_strategy_id,
    fsh_cq_check as requirement_relevant,
    xegdr as eu_triangular_deal,
    bstnk as customer_purchase_order_number,
    multi as multiple_promotions,
    sppaym as payment_method,
    lifsk as delivery_block_document_header_id,
    fsh_kvgr9 as customer_group_9_id,
    aedat as changed_date,
    wtysc_clm_hdr as claim_header,
    dat_fzau as cml_delivery_order_qty_date,
    awahr as sales_probability,
    kurst as exchange_rate_type_id,
    gueen as valid_to_date,
    _xlso_so_vald_to as _xlso_so_vald_to,
    cmnup as next_check_date,
    abhod as pick_up_date,
    vkorg as sales_organization_id,
    audat as document_date,
    zuonr as assignment_number,
    angdt as quotation_inquiry_is_valid_from_date,
    vsbed as shipping_conditions_id,
    _xlso_payment_op as _xlso_payment_op,
    rep_freq as reporting_frequency,
    handle as int_id,
    _xlso_so_vald_fm as _xlso_so_vald_fm,
    bstzd as purchase_order_number_supplement,
    taxk1 as alternative_tax_classification_id,
    mahdt as last_customer_contact_date,
    bstdk as customer_purchase_order_date,
    vbeln_grp as mster_contract_number_id,
    handoverloc as handover_location,
    qmnum as notification_id,
    kalsm_ch as search_procedure_id,
    cont_dg as contains_dg,
    cmfre as release_date,
    vtweg as distribution_channel_id,
    telf1 as telephone_number,
    aufnr as order_id,
    phase as sales_phase_id,
    taxk2 as taxclass2_cust_id,
    kvgr1 as customer_group_1_id,
    grupp as customer_credit_group_id,
    fsh_os_stg_change as os_strategy_specific_fields_change,
    abhob as abhob,
    landtx as tax_departure_country_id,
    kalsm as pricing_procedure_id,
    erdat as created_date,
    bpn as business_partner_number_id,
    stage as construction_stage,
    kkber as credit_control_area_id,
    taxk3 as taxclass3_cust_id,
    abrvw as usage_id,
    vbtyp as sd_document_category,
    kvgr2 as customer_group_2_id,
    knumv as document_condition_no,
    guebg as valid_from_date,
    fsh_vas_cg as vas_customer_group_id,
    waerk as sd_document_currency_id,
    vkbur as sales_office_id,
    ctlpc as credit_management_risk_category_id,
    vsnmr_v as sales_document_version_number,
    rplnr as number_payment_card_plan_type_id,
    vbklt as sd_document_indicator,
    mod_allow as modification_allowed,
    taxk4 as tax_classification_4_customer_id,
    _xlso_catalog_id as _xlso_catalog_id,
    kvgr3 as customer_group_3_id,
    fsh_candate as cancellation_date,
    agrzr as accrual_period,
    mill_appl_id as application_id,
    bsark as customer_purchase_order_type_id,
    tm_ctrl_key as control_key,
    gsber as business_area_id,
    _fivetran_deleted as _fivetran_deleted,
    _fivetran_synced as _fivetran_synced,
    _fivetran_sap_archived as _fivetran_sap_archived
from "sap"."main_sap"."stg_sap__vbak"
),  __dbt__cte__int_sap__sales_document_item as (


select
    mandt as client_id,
    posnr as sales_document_item_id,
    vbeln as sales_document_id,
    smeng as scale_quantity,
    stlty as bom_category,
    vgref as preceding_document_resulted_from_ref,
    bwtar as valuation_type_id,
    knuma_ag as sales_deal_id,
    spart as division_id,
    bwtex as indicator_separate_valuation,
    oih_licin as internal_license_no_id,
    oic_dcounc as destination_county_code_id,
    knuma_pi as promotion_id,
    oic_dcityc as destination_city_code_id,
    tas as treasury_account_symbol,
    oignrule as gross_net_pricing_rule_id,
    upmat as mnitm_prcrefmatl_id,
    kalsm_k as costing_sheet_id,
    oicertf1_ex as external_license_no,
    aplzl_olc as counter,
    umvkn as denominator,
    oidmsg_qty as quantity_message,
    kever as deviation_days,
    mtvfp as availability_check_id,
    oihantyp_ex as handling_type_id,
    abgru as reason_rejection_id,
    xchar as batch_management,
    kostl as cost_center_id,
    _accgo_tx_p as _accgo_tx_p,
    prs_work_period as work_period,
    vkgru as repair_classification_items_id,
    wktnr as value_contract_no_id,
    absfz as absolute_deviation,
    oih_lcfol as follow_on_license_id,
    vbeaf as fixed_process_time,
    ernam as created_by,
    oitaxfrom_im as tax_key_from_id,
    stafo as update_group_stats_id,
    oic_lifnr as vendor_id,
    j_1btxsdc as sd_tax_code_id,
    taxm1 as tax_classification_id,
    lprio as delivery_priority_id,
    oiedbalm_ex as balance_method_ind,
    umziz as conversion_factor,
    kzvbr as consumption_posting,
    oic_aorgin as alternate_origin,
    _slce_inst_guid as _slce_inst_guid,
    charg as batch_id,
    stlkn as bom_item_node_number,
    fsh_collection as fashion_collection_id,
    cmeth as quantity_conversion_method,
    aplzl_oaa as aplzl_oaa,
    oidmsg_dat as validity_date_msg,
    umvkz as numerator,
    oitaxgrp_ex as excise_duty_group_id,
    fsh_candate as cancellation_date,
    oipricie_im as ed_pricing_external,
    _slce_sol_posnr as _slce_sol_posnr,
    tax_subject_st as tax_subject_to_substituicao_tributaria,
    gewei as weight_uom_id,
    revacc_refid as revenue_accounting_reference_id,
    oic_porgin as tax_origin,
    sobkz as special_stock_id,
    vpwrk as planning_plant_id,
    waerk as sd_document_currency_id,
    mod_allow as modification_allowed,
    umzin as umzin,
    magrv as matl_grp_pack_matls_id,
    oic_pbatch as pipe_ex_batch_no,
    bonus as volume_rebate_group_id,
    sloctype as location_type,
    oiedbal_im as ed_balance_indicator,
    fsh_vas_prnt_id as sd_item_id,
    ablfz as rounding_quantity_delivery,
    taxm3 as taxm3,
    pstyv as sales_document_item_category_id,
    _xlso_course_eda as _xlso_course_eda,
    fiscal_incentive as tax_incentive_type_id,
    oic_mot as mode_transport_id,
    oic_oregio as origin_region_id,
    fistl as funds_center_id,
    vpmat as planning_material_id,
    awahr as order_probability_the_item,
    kpein as condition_pricing_unit,
    voleh as volume_uom_id,
    werks as plant_own_or_external_id,
    oicertf1 as oicertf1,
    knumh as no_cond_rec_batch,
    taxm2 as taxm2,
    fsh_psm_pfm_split as psm_and_pfm_split_id,
    tc_aut_det as tax_code_automatically_determined_id,
    serail as serial_number_profile_id,
    kosch as product_allocation_id,
    oid_miscdl as miscellaneous_delivery_number,
    oih_lictp_ex as license_type_id,
    paobjnr as profitability_segment_no,
    ps_psp_pnr as wbs_element_id,
    rkfkf as billing_meth_co_ppc,
    sktof as cash_discount_indicator,
    fkrel as relevant_billing,
    oihantyp as oihantyp,
    _slce_sol_matnr as _slce_sol_matnr,
    oiplantd as is_oil_plant_determ,
    lstanr as free_goods_delivery_control,
    _dataaging as filter_value_aging_date,
    cpd_updat as time_stamp,
    oic_drcreg as drc_region_id,
    bedae as requirements_type_id,
    manual_tc_reason as manual_tax_code_reason_id,
    spcsto as nf_cfop_special_case_id,
    aedat as changed_date,
    z_prs_offshore as on_near_offshore_delivery_type,
    kzwi1 as subtotal_1_val,
    oiedok as excise_duty_validation_indicator,
    fsh_pqr_uepos as higher_lev_item_partial_quantity_rej_id,
    handovertime as handover_tim,
    xchpf as xchpf,
    oibwtar_im as oibwtar_im,
    shkzg as returns_item,
    _slce_sol_cuobj as _slce_sol_cuobj,
    aufpl_olc as operation_task_list_no,
    ntgew as net_weight_the_item,
    vgtyp as preceding_doc_categ,
    stockloc as location,
    pmatn as pricing_reference_material_id,
    sernr as bom_explosion_number_id,
    taxm4 as taxm4,
    kalnr as cost_estimate_number_id,
    oiexgnum as exchange_agreement_number_id,
    erlre as completion_rule,
    oiexgtyp as exchange_type_id,
    oitaxto_im as tax_key_to_id,
    kzbws as special_stock_valuation,
    _accgo_is_co_rel as _accgo_is_co_rel,
    pargb as trading_partba_id,
    oimetind as metropolitan_indicator_id,
    oih_folqty as _2nd_license_qty,
    oic_truckn as truck_number,
    uebtk as unlimited_overdelivery_allowed,
    arsnum as reservation_id,
    kdmat as material_number_used_by_customer,
    bpn as business_partner_number_id,
    mvgr1 as material_group_1_id,
    voref as complete_reference_indicator,
    erzet as created_tim,
    arktx as short_text_sales_order_item,
    cmpnt as credit_funct_active,
    oihnotlgort as storage_loc_id,
    uepos as higher_level_item_id,
    stdat as key_the_bill_material_date,
    stcur as exchange_rate_stats,
    oitaxfrom_ex as oitaxfrom_ex,
    fiscal_incentive_id as incentive_id,
    _slce_single_conf_done as _slce_single_conf_done,
    klmeng as cumul_confirmed_qty,
    zmeng as target_quantity_in_sales_units,
    oidrc as differ_refer_code_id,
    pay_method as payment_methods,
    _slce_sol_ext_guid as _slce_sol_ext_guid,
    kzwi2 as subtotal_2_val,
    oibypass as is_oil_plt_det_ind,
    fsh_item_group as item_group,
    aufpl_oaa as aufpl_oaa,
    kwmeng as order_quantity,
    oih_lcfol_ex as oih_lcfol_ex,
    koupd as condition_update,
    fsh_grid_cond_rec as grid_condition_number,
    techs as standard_variant,
    matnr as material_id,
    wgru1 as material_group_hierarchy_1,
    oitaxfrom as oitaxfrom,
    taxm5 as taxm5,
    kztlf as partial_delivery_at_item_level,
    iuid_relevant as iuid_relevant_customer,
    oic_kmpos as ref_contract_item,
    z_prs_country as country_key_id,
    gsber as business_area_id,
    oipricie_ex as oipricie_ex,
    fsh_crsd as condition_no,
    fsh_transaction as transaction_number,
    grkor as delivery_group,
    uepvw as id_higher_level_item_usage,
    mfrgr as material_freight_group_id,
    vbelv as originating_document_id,
    untto as underdelivery_tolerance_limit,
    plavo as plandelschedinstruct_id,
    vpzuo as allocation_indicator,
    mvgr3 as material_group_3_id,
    sugrd as reason_material_substitution_id,
    oic_ptrip as pipeline_trip_number_external,
    oic_adestn as alternate_destination,
    oic_oland1 as origin_country_id,
    mvgr2 as material_group_2_id,
    netpr as net_price_val,
    oicontnr as outline_agreement_contract_id,
    stman as inconsistent_configuration,
    oiedbal_ex as oiedbal_ex,
    j_1btaxlw3 as iss_tax_law_id,
    _slce_single_conf_reqired as _slce_single_conf_reqired,
    oinetcyc as netting_cycle_id,
    prsok as pricing_is_ok,
    vgpos as reference_item_id,
    cuobj_ch as internal_object_no,
    oic_pdestn as tax_destination,
    rep_freq as reporting_frequency,
    lsmeng as required_deliv_qty,
    stpoz as stpoz,
    kzwi3 as subtotal_3_val,
    posar as item_type,
    budget_pd as budget_period_id,
    z_prs_chargelevl as staff_grade,
    posnv as originating_item_id,
    wgru2 as material_group_hierarchy_2,
    oifeetot as fee_total_val,
    oic_dregio as destination_region_id,
    oih_licin_ex as oih_licin_ex,
    oioilcon as oil_content_perc,
    aufnr as order_id,
    sgt_rcat as requirement_segment,
    oidmsg_uom as unit_measure_msg,
    oibasprod as base_product_number_id,
    msr_refund_code as returns_refund_code_id,
    cuobj as configuration,
    kbver as deviation_in_percent,
    sposn as bom_item_number,
    fsh_season_year as season_year_id,
    zzdea_license as dea_number,
    taxm6 as taxm6,
    mprok as status_manual_price_change,
    provg as commission_group_id,
    oitaxto as oitaxto,
    cmkua as cred_exch_rate,
    cmtfg as partial_release,
    oid_extbol as external_bill_lading,
    ukonm as mnitem_matpricinggrp_id,
    mvgr4 as material_group_4_id,
    kmein as condition_uom_id,
    klvar as costing_variant_id,
    prs_sd_spsnr as standard_wbs_element_id,
    mwsbp as tax_amount_document_currency_val,
    revacc_reftype as rev_acc_reference_type,
    wrf_charstc1 as characteristic_value_1,
    fsh_item as item_number,
    skopf as assortment_module_id,
    oibwtar_ex as oibwtar_ex,
    prodh as product_hierarchy_id,
    stkey as origin_the_bill_material,
    j_1btaxlw4 as cofins_tax_law_id,
    route as route_id,
    _xlso_course_bda as _xlso_course_bda,
    matkl as material_group_id,
    oic_drctry as drc_country_id,
    kalvar as kalvar,
    lfrel as item_is_relevant_delivery,
    kmpmg as component_quantity,
    kzwi4 as subtotal_4_val,
    wtysc_clmitem as claim_item_number,
    fmeng as quantity_is_fixed,
    nrab_knumh as condition_number,
    oitaxto_ex as oitaxto_ex,
    cmpre as item_credit_price_val,
    handoverdate as handover_date,
    nachl as no_gr_posted_by_cst,
    abdat as reconciliation_date,
    kondm as material_pricing_group_id,
    oic_dland1 as destination_country_id,
    cmpre_flt as item_credit_price,
    taxm7 as taxm7,
    ferc_ind as regulatory_indicator_id,
    oifeech as fee_edit_control,
    oih_folqty_ex as oih_folqty_ex,
    prctr as profit_center_id,
    eannr as ean_number,
    zschl_k as overhead_key,
    oislf as state_license_fee_zone_id,
    pctrf as profit_center_billing_id,
    fsh_vas_rel as vas_relevant,
    mvgr5 as material_group_5_id,
    fkber as functional_area_id,
    vbeav as var_processing_time,
    zwert as oa_target_val,
    antlf as max_part_deliveries,
    cancel_allow as cancellation_allowed,
    fsh_searef as copied_season,
    oipricie as oipricie,
    wrf_charstc2 as characteristic_value_2,
    upflu as update_document_flow,
    oihcotdisch as imp_posting_at_pod,
    oidmsg_shp as ship_to_party_msg,
    grant_nbr as _grant,
    oidmsg_trm as payment_terms_msg,
    umref as conversion_factor_quantities,
    kzwi6 as subtotal_6_val,
    knttp as account_assignment_category_id,
    j_1btaxlw5 as pis_tax_law_id,
    stlnr as bill_material,
    vkaus as usage_id,
    erdat as created_date,
    kzwi5 as subtotal_5_val,
    fsh_theme as fashion_theme_id,
    fsh_season as season_id,
    zieme as target_quantity_uom_uom_id,
    oipsdrc as pricing_drc_id,
    uebto as overdelivery_tolerance_limit,
    grpos as alternative_to_item,
    chmvs as quantity_proposal,
    oihantyp_im as oihantyp_im,
    abges as guaranteed,
    oihnotwerks as cross_excise_duty_plant_id,
    z_prs_bill_flag as billable_non_billable,
    abgrs as results_analysis_key_id,
    taxm8 as taxm8,
    objnr as object_number_at_item_level_id,
    volum as volume_the_item,
    oiinex_ex as ed_pricing_key_id,
    j_1btaxlw1 as icms_law_id,
    j_1bcfop as cfop_code_and_extension_id,
    kowrr as statistical_values,
    fixmg as delivery_date_and_quantity_fixed,
    _xlso_course_id as _xlso_course_id,
    fmfgus_key as us_government_fields,
    atpkz as replacement_part,
    oifeedt as fee_pricing_condition_date,
    meins as base_uom_id,
    oiinex as oiinex,
    msr_ret_reason as return_reason_id,
    handoverloc as handover_location,
    lfmng as minimum_delivery_qty,
    ktgrm as acct_assignment_grp_id,
    oia_baselo as base_location,
    betc as business_event_type_code,
    wrf_charstc3 as characteristic_value_3,
    oiedbalm_im as oiedbalm_im,
    oihtaxrcp_ex as tax_recipient,
    oic_ocounc as origin_county_code_id,
    exart as bus_transaction_type_id,
    fsh_vasref as copied_vas,
    oiwap as wide_area_pricing_zone_id,
    vgbel as reference_document_id,
    kannr as kanban_sequence_number,
    sumbd as summing_up_requirements,
    oidmsg_prd as products_message,
    posex as purchase_order_item,
    oitaxgrp_im as oitaxgrp_im,
    oic_ocityc as origin_city_code_id,
    oid_ship as ship_to_party_id,
    prosa as id_material_determination,
    berid as mrp_area_id,
    logsys_ext as logical_system_id,
    oipipeval as val_ind_pipeline,
    oitaxgrp as oitaxgrp,
    vrkme as sales_uom_id,
    ean11 as ean,
    taxm9 as taxm9,
    kzfme as leading_uom,
    wktps as value_contract_item_id,
    j_1btaxlw2 as ipi_law_id,
    oiedbalm as oiedbalm,
    stpos as bill_material_item_number,
    anzsn as number_serial_numbers,
    oisbrel as s_b_prod_relev_ind,
    oih_lictp as oih_lictp,
    wavwr as cost_document_currency_val,
    arspos as item_no_reservation,
    _bev1_srfund as _bev1_srfund,
    netwr as net_val,
    prs_objnr as engagement_mgmt_object_number,
    kbmeng as kbmeng,
    prefe as preference_auth,
    prbme as product_group_uom_id,
    clint as internal_class_number_id,
    zzdea_schedule as dea_schedule_key,
    oiedbal as oiedbal,
    trmrisk_relevant as risk_relevancy_in_sales,
    chspl as batch_split_allowed,
    matwa as material_entered_id,
    faksp as billing_block_item_id,
    fonds as fund_id,
    brgew as gross_weight_the_item,
    abfor as form_payment_guarantee_id,
    stadat as statistics_date,
    vstel as shipping_point_id,
    mill_se_gposn as global_item_id,
    lgort as storage_location_id,
    msr_approv_block as approval_block,
    cepok as status_expected_price,
    _fivetran_deleted as _fivetran_deleted,
    _fivetran_synced as _fivetran_synced,
    _fivetran_sap_archived as _fivetran_sap_archived
from "sap"."main_sap"."stg_sap__vbap"
),  __dbt__cte__int_sap__sales_document_header_status as (


select
    mandt as client_id,
    vbeln as sales_document_id,
    rfstk as reference_document_header_status,
    rfgsk as total_reference_stat,
    bestk as confirmation_status,
    lfstk as delivery_status,
    lfgsk as overall_dlv_status,
    wbstk as total_goods_movement_status,
    fkstk as billing_status,
    fksak as bill_stat_order_rel,
    buchk as posting_status,
    abstk as rejection_status,
    gbstk as overall_status,
    kostk as overall_picking_putaway_status,
    lvstk as overall_wm_status,
    uvals as item,
    uvvls as item_delivery,
    uvfas as item_billing,
    uvall as header,
    uvvlk as header_delivery,
    uvfak as header_billing,
    uvprs as pricing,
    vbtyp as sd_document_category,
    vbobj as sd_document_object,
    
    to_date(cast(aedat as TEXT), 'YYYYMMDD')
 as changed_date,
    fkivk as totals_status,
    relik as inv_list_status,
    uvk01 as header_reserves_1,
    uvk02 as header_reserves_2,
    uvk03 as header_reserves_3,
    uvk04 as header_reserves_4,
    uvk05 as header_reserves_5,
    uvs01 as total_reserves_1,
    uvs02 as total_reserves_2,
    uvs03 as total_reserves_3,
    uvs04 as total_reserves_4,
    uvs05 as total_reserves_5,
    pkstk as packing_status,
    cmpsa as static_check,
    cmpsb as dynamic_check,
    cmpsc as maximum_value,
    cmpsd as terms_payment,
    cmpse as customer_review_date,
    cmpsf as overdue_open_items,
    cmpsg as oldest_open_items,
    cmpsh as max_dunning_level,
    cmpsi as financial_document,
    cmpsj as expt_cred_insurance,
    cmpsk as payment_card,
    cmpsl as reserve,
    cmps0 as cmps0,
    cmps1 as cmps1,
    cmps2 as cmps2,
    cmgst as overall_status_credit_checks,
    trsta as transportation_planning_status,
    koquk as status_pick_confirmation,
    costa as confirmation_status_ale,
    saprl as sap_release,
    uvpas as it_packaging,
    uvpis as it_picking_putaway,
    uvwas as item_goods_mvmt,
    uvpak as head_packaging,
    uvpik as head_picking_putaway,
    uvwak as head_goods_mvmt,
    uvgek as unused,
    cmpsm as credit_check_is_obsolete,
    dcstk as delay_status,
    vestk as handling_unit_placed_in_stock,
    vlstk as status_decent_whse,
    rrsta as revenue_determination_status,
    block as block,
    fsstk as overall_billing_block_status,
    lsstk as overall_delivery_block_status,
    spstg as overall_blocked_status,
    pdstk as pod_status_on_header_level,
    fmstk as status_funds_management,
    manek as manual_completion_contract,
    spe_tmpid as temporary_inbound_delivery,
    hdall as on_hold,
    hdals as pos_hold,
    cmps_cm as sap_credit_management,
    cmps_te as credit_mgmt_te_status,
    vbtyp_ext as doc_cat_extension,
    fsh_ar_stat_hdr as arun_status_at_header,
    hvr_is_deleted as hvr_is_deleted,
    hvr_change_time as hvr_change_time
from "sap"."main_sap"."stg_sap__vbuk"
),  __dbt__cte__int_sap__sales_document_item_status as (


select
    mandt as client_id,
    posnr as sd_item_id,
    vbeln as sales_document_id,
    uvpak as item_packaging,
    uvvlk as item_deliv,
    mill_vs_vssta as status_sales_order_item,
    pksta as packing_status_item,
    lssta as delivery_block_status_item,
    vlstp as decentralized_whse_processing,
    absta as rejection_status_sd_item,
    fksta as billing_status,
    fkivp as intercompany_billing_status,
    lfgsa as overall_deliv_status,
    rrsta as revenue_determination_status,
    lfsta as delivery_status,
    fksaa as ord_related_bill_st,
    wbsta as goods_movement_status,
    ltsps as stockable_type_switched_into_stand_prod,
    costa as confirmation_status_ale,
    fssta as billing_block_status_items,
    kosta as picking_status_putaway_status,
    uvpik as item_picking_putaway,
    uvfak as item_billing,
    uvall as item,
    rfgsa as overall_status_reference,
    uvprs as pricing_item_is_incomplete,
    lvsta as wm_activity_status,
    rfsta as reference_status,
    cmppj as expt_cred_insurance,
    cmppi as financial_document,
    hdall as delivery_item_not_complete,
    besta as confirmed,
    pdsta as pod_status_on_item_level,
    fsh_ar_stat_itm as arun_status_item_level,
    manek as manual_completion_contract,
    gbsta as overall_status,
    uvwak as item_goods_mvmt,
    dcsta as delay_status,
    uvp05 as customer_reserves_5_item_status,
    uvp02 as customer_reserves_2_item_status,
    uvp04 as item_reserves_4_item_status,
    koqua as pick_confirmation,
    uvp01 as customer_reserves_1_item_status,
    uvp03 as item_reserves_3_item_status,
    _fivetran_deleted as _fivetran_deleted,
    _fivetran_synced as _fivetran_synced,
    _fivetran_sap_archived as _fivetran_sap_archived
from "sap"."main_sap"."stg_sap__vbup"
), sales_document_header as (
    select *
    from __dbt__cte__int_sap__sales_document_header


), sales_document_item as (
    select *
    from __dbt__cte__int_sap__sales_document_item



), sales_document_header_status as (
    select *
    from __dbt__cte__int_sap__sales_document_header_status



), sales_document_item_status as (
    select *
    from __dbt__cte__int_sap__sales_document_item_status


), final as (
    select
        ltrim(sales_document_header.sales_document_id, '0') as sales_document_number,
        sales_document_header.sd_document_category,
        sales_document_header.sales_document_type_id,
        sales_document_header.order_reason_id,
        sales_document_header.delivery_block_document_header_id as delivery_block_id,
        sales_document_header.sales_organization_id,
        sales_document_header.distribution_channel_id,
        sales_document_header.division_id,
        sales_document_header.document_date,
        sales_document_header.requested_delivery_date,
        sales_document_header.sold_to_party_id as sold_to_customer_id,
        sales_document_header.sales_document_id,
        sales_document_header.created_date,
        sales_document_header.created_by

        
        , ltrim(sales_document_item.sales_document_item_id, '0') as sales_document_item
        , sales_document_item.plant_own_or_external_id as plant_id
        , sales_document_item.material_id
        , sales_document_item.material_group_id
        , sales_document_item.sales_document_item_category_id
        , sales_document_item.product_hierarchy_id
        , sales_document_item.base_uom_id
        , case
            when sales_document_header.sd_document_category = 'c' then sales_document_item.order_quantity
            else sales_document_item.order_quantity * -1
        end as order_quantity
        , sales_document_item.sales_uom_id
        , case
            when sales_document_header.sd_document_category = 'c' then sales_document_item.net_val
            else sales_document_item.net_val * -1
        end as net_value
        , sales_document_item.net_price_val as net_price
        , sales_document_item.sd_document_currency_id
        , sales_document_item.gross_weight_the_item as gross_weight
        , sales_document_item.weight_uom_id
        , sales_document_item.returns_item
        , sales_document_item.reason_rejection_id
        , sales_document_item._fivetran_deleted
        , sales_document_item._fivetran_synced
        

        
        , sales_document_header_status.delivery_status
        , sales_document_header_status.overall_status
        

        
        , sales_document_item_status.delivery_status as item_delivery_status
        

    from sales_document_header

    
    inner join sales_document_item
        on sales_document_header.sales_document_id = sales_document_item.sales_document_id
    

    
    inner join sales_document_header_status
        on sales_document_header.sales_document_id = sales_document_header_status.sales_document_id
    

    
    inner join sales_document_item_status
        on sales_document_item.sales_document_id = sales_document_item_status.sales_document_id
        and sales_document_item.sales_document_item_id = sales_document_item_status.sd_item_id
    

    where sales_document_header.sd_document_category in ('c', 'h')
)

select *
from final
