ecommerce_analytics:
  target: duckdb
  outputs:
    datafusion:
      type: datafusion
      path: target/ecommerce.db
      schema: main
      threads: 1
    duckdb:
      type: duckdb
      path: target/ecommerce.duckdb
      schema: main
      threads: 1
