[package]
name = "airform-executor"
version.workspace = true
edition.workspace = true

[dependencies]
airform-core.workspace = true
airform-compiler.workspace = true
airform-graph.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
datafusion.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
async-trait.workspace = true
ureq.workspace = true
dotenvy.workspace = true
chrono.workspace = true
duckdb = { workspace = true }
tokio-postgres = { workspace = true }
mysql_async = { workspace = true }
