scale_1000:
  target: duckdb
  outputs:
    datafusion:
      type: datafusion
      path: target/scale_1000.db
      schema: main
      threads: 1
    duckdb:
      type: duckdb
      path: target/scale_1000.duckdb
      schema: main
      threads: 1
